#!/bin/bash
IFS=$'\n'

#    .---------- constant part!
#    vvvv vvvv-- the code from above
RED='\033[0;31m'
NC='\033[0m' # No Color

for f in $(find . -name '*.mkv');
do if [[ $(ffprobe -v error "$f" 2>&1 | grep -E '[[:alnum:]]+') ]]; then

        printf "${RED}Errors Found...in '$f' ${NC}\n"
        printf "${RED}Parsing to ffmpeg...${NC}\n"
        ffmpeg -y -i "$f" -c copy -crf 0 -map 0 "${f%.*}-FIXED.mkv"
        echo "$f" >> files-fixed.log
        #rm -rf "$f"
   else
        echo "${NC} $f File Ok"
fi
done
unset IFS
